kind: pipeline
type: docker
name: Localstack Terratest Test

trigger:
  branch:
  - main

services:
- name: localstack
  image: localstack/localstack:0.14.3

steps:

- name: write vars
  image: alpine
  commands:
  - ls 
  - pwd
  - echo MY_VAR=myvalue > sourceme

- name: read vars
  image: alpine
  commands:
  - ls
  - pwd
  - source sourceme
  - echo $MY_VAR
  - exit 1


# disabling AWS tests for the talk
# 
#---
#kind: pipeline
#type: docker
#name: AWS Terratest Test
#
#trigger:
#  when:
#    status:
#    - failure
#    - success
#  branch:
#  - main
#
#steps:
#
#- name: run tests
#  image: hashicorp/terraform:1.2.2
#  environment:
#    AWS_ACCESS_KEY_ID: ASIARLPW64RANAXCCYHT
#    AWS_SESSION_TOKEN:
#      from_secret: aws_session_token
#    AWS_SECRET_ACCESS_KEY:
#      from_secret: aws_secret_access_key
#  commands:
#  - apk add go
#  # copy AWS provider config into place
#  - cp tests/aws-provider.tf test-provider.tf
#  - cd tests
#  - go test -v -run TestTerraformAwsNetworkExample
#
#---
#kind: pipeline
#type: docker
#name: AWS Terraform CLI Test
#
#depends_on:
#- "AWS Terratest Test"
#
#trigger:
#  when:
#    status:
#    - failure
#    - success
#  branch:
#  - main
#
#steps:
#
#- name: run tests
#  image: hashicorp/terraform:1.2.2
#  environment:
#    AWS_ACCESS_KEY_ID: ASIARLPW64RANAXCCYHT
#    AWS_SESSION_TOKEN:
#      from_secret: aws_session_token
#    AWS_SECRET_ACCESS_KEY:
#      from_secret: aws_secret_access_key
#  commands:
#  # copy AWS provider config into place
#  - cp tests/aws-provider.tf tests/example/test-provider.tf
#  - terraform test
