kind: pipeline
type: docker
name: Localstack Terratest

trigger:
  branch:
  - main

workspace:
  base: /go
  path: src/github.com/jimsheldon/terraform-aws-network-example

services:
- name: localstack
  image: localstack/localstack:0.14.3

steps:
- name: localstack wait
  image: alpine/curl:3.14
  commands:
  # Checks to see that localstack service is up and running
  - until curl -s http://localstack:4566/health; do echo -n . && sleep 1; done

- name: go get
  image: golang:1.18
  commands:
  - cd tests
  - go get

- name: go test
  image: golang:1.18
  commands:
  - cd tests
  - go test -v -run TestTerraformAwsNetworkExample

---  
kind: pipeline
type: docker
name: Localstack Terraform CLI

trigger:
  branch:
  - main

services:
- name: localstack
  image: localstack/localstack:0.14.3

steps:

- name: localstack wait
  image: alpine/curl:3.14
  commands:
  # Checks to see that localstack service is up and running
  - until curl -s http://localstack:4566/health; do echo -n . && sleep 1; done

- name: terraform test
  image: hashicorp/terraform:1.2.2
  commands:
  - cp tests/aws-provider-localstack.tf tests/example/test-provider.tf
  - terraform test
 
